// One-time vendoring step: pulls brand glyph paths from simple-icons (CC0) into
// scripts/icons.mjs so rendering never depends on a CDN being up. Re-run to refresh.
import { writeFileSync } from 'node:fs';

const TECH = [
  ['java',       'openjdk',     'Java'],
  ['spring',     'springboot',  'Spring Boot'],
  ['laravel',    'laravel',     'Laravel'],
  ['typescript', 'typescript',  'TypeScript'],
  ['react',      'react',       'React'],
  ['next',       'nextdotjs',   'Next.js'],
  ['vue',        'vuedotjs',    'Vue'],
  ['node',       'nodedotjs',   'Node.js'],
  ['go',         'go',          'Go'],
  ['swift',      'swift',       'Swift'],
  ['python',     'python',      'Python'],
  ['astro',      'astro',       'Astro'],
  ['postgres',   'postgresql',  'PostgreSQL'],
  ['mysql',      'mysql',       'MySQL'],
  ['docker',     'docker',      'Docker'],
  ['gcloud',     'googlecloud', 'Google Cloud'],
];

// Preserved across refreshes so a re-fetch does not lose the measured optical sizes.
const { ICONS: PREV } = await import('./icons.mjs').catch(() => ({ ICONS: {} }));
const TECH_BBOX = Object.fromEntries(Object.entries(PREV).map(([k, v]) => [k, v.bbox]));

const out = {};
for (const [key, slug, label] of TECH) {
  const res = await fetch(`https://cdn.jsdelivr.net/npm/simple-icons@13/icons/${slug}.svg`);
  if (!res.ok) throw new Error(`${slug}: ${res.status}`);
  const svg = await res.text();
  const d = svg.match(/ d="([^"]+)"/)?.[1];
  if (!d) throw new Error(`${slug}: no path found`);
  // bbox is filled in by the browser measuring step — see icons.mjs header.
  out[key] = { label, d, bbox: TECH_BBOX[key] ?? [0, 0, 24, 24] };
  console.log(`${slug.padEnd(12)} ${d.length} chars`);
}

writeFileSync(new URL('icons.mjs', import.meta.url),
  '// Generated by fetch-icons.mjs from simple-icons (CC0). Do not hand-edit.\n'
  + '// Glyphs are drawn in a 24x24 viewBox.\n'
  + `export const ICONS = ${JSON.stringify(out, null, 2)};\n`);
console.log(`\nwrote ${Object.keys(out).length} icons`);
